### ISSUE TITLE
Queue Commands

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#10]
This is a question. There is 'Queue' context menu with sub-commands:

- Move To Top
- Move Up
- Move Down
- Move To Bottom

but these sub-commands are inaccessible (grayed out), screen:

![http downloader 1 0 0 7 - 2018-09-30 - queue - 001](https://user-images.githubusercontent.com/9025757/46261322-b279e080-c4fa-11e8-9230-7c4d0d27543c.png)

Why these commands are not accessible? They are supposed to work only with active downloads?

**Comment by smaragdus** [comment]
I set 'Active download limit' to 0 and then to 1 yet these queue commands ('Move To Top', 'Move Up', 'Move Down', 'Move To Bottom') while active did not work. Can you please confirm that?

**Comment by erickutcher** [comment]
The queue order isn't visible and the items don't actually move in the list. The only way you'll see anything is if the program is downloading something. I suppose I could make a column that shows the queue index. That would be for another time though.

Here's what I did to test things.

I set the active downloads to 0 and added three files. All three get queued in the list. I then set the first item's queue position to "Move to Bottom" and I set the third item's queue position to "Move to Top". I then set the active downloads to 1 and manually started the third item.

The third item downloaded, then the second, and finally the first. That should be the expected behavior.

**Comment by JNavas2** [comment]
> The queue order isn't visible and the items don't actually move in the list. The only way you'll see anything is if the program is downloading something. I suppose I could make a column that shows the queue index. That would be for another time though.

Please do so. Not being able to see the queue order is seriously confusing. I was about to enter a bug because downloads were not following the GUI order. Thank you.
