### ISSUE TITLE
Tray Icon Suggestion

### ISSUE THREAD

**Issue by sick13** [erickutcher/httpdownloader#104]
Could we get a different icon style in the sys tray?

maybe it could use an approach as utorrent does [place an *.ico where the *.exe is and it would pick it up] or say an all white icon with the progress,this just personal request and for those who use the dark themes.

easier on the eyes than current blue one in my opinion

**Comment by erickutcher** [comment]
I suppose I could do it similarly to how I have the toolbar icons set up. A standalone ico file in the same directory will make things consistent and you'll be able to create your own icon (since I hate drawing).

**Comment by erickutcher** [comment]
I made it so that it'll load two icons, main.ico and tray.ico, from the same folder as the program.

main.ico is the icon that's used for all the windows and is also the default tray icon (when it's not set to show a progress bar).

tray.ico is the icon that's used when the tray icon has a progress bar. You'll notice that this icon has a 16x4 black box at the bottom of it. This is where the progress bar gets drawn. The progress and border colors can now be set in the Appearance options. The color is determined by the Downloading, Paused, and Failed progress and border colors.

Here's a couple links to the default icons. You should be able to modify them however you like.
Rename this to main.ico https://github.com/erickutcher/httpdownloader/raw/master/HTTP_Downloader/icon.ico
Rename this to tray.ico https://github.com/erickutcher/httpdownloader/raw/master/HTTP_Downloader/icon_tray.ico

This will be available in the next release.

**Comment by sick13** [comment]
nice thank you! as for tray icons some one more able is going to pick up the drawing work! but anyway thx for the option!

**Comment by erickutcher** [comment]
Here's some icons that should look decent on a dark mode desktop: [Dark_Icons.zip](https://github.com/erickutcher/httpdownloader/files/4081527/Dark_Icons.zip)

The URL Drop window's background image can also be changed. It's a 48x48 bitmap called drop.bmp 

Put them in the same folder as the program.

The latest version is up.
