### ISSUE TITLE
Transparent window and Allocating File

### ISSUE THREAD

**Issue by RatError** [erickutcher/httpdownloader#105]
Version 1.0.2.9 some  bugs.
1. After some, long work time when adding links to the URL drop  window, the Add URL(s) window appears - but it is transparent ...
Helps minimize and maximize a window.
2. After a loading error, for example, in the absence of a consolidated space, the indication freezes at Allocating File, while the start and restart actions are not active. And only after rebooting the program, it changes to the File IO Error, and then it is possible to restart the download.
Perhaps this is due to the large download history of ~ 20k records?

![URL Drop Window](https://user-images.githubusercontent.com/58669239/72219588-c06d3c80-3558-11ea-8273-9e2f676f6ccc.jpg)

![HTTP_D](https://user-images.githubusercontent.com/58669239/72219577-a5023180-3558-11ea-8783-dc95d416d690.png)

**Comment by erickutcher** [comment]
I'm not sure why the window would turn transparent all of a sudden. Sounds like a Windows bug to me. The Add URL(s) window is created with the WS_EX_COMPOSITED flag. I had to use that to prevent some nasty flickering. I also have the background color of the tab control repainted so that it looks nice on Windows XP systems. That shouldn't affect the whole window though.

As for the allocating issue, it probably failed to write the initial byte that triggers Windows to actually allocate the space on the disk. I see in the code where that could happen and I've corrected it. Now when it fails to allocate it'll display File IO Error instead of being stuck with Allocating File.

You could also speed up the allocation process by enabling quick file allocation in the Advanced options. It requires the program to be run as an Administrator though.

**Comment by RatError** [comment]
On versions 1.0.2.0-1.0.2.6, a bug with a window never appeared. 
Perhaps somewhere in the latest versions.
And it does not appear during standard work through a click or the Chrome context menu, but only when adding links through the floating URL drop icon.
If important: Win 10 1607
Thanks for the good program.

**Comment by erickutcher** [comment]
It's most likely the WS_EX_COMPOSITED flag that's set when the Add URL(s) window is created. From what I've read elsewhere, there's a bug with early Windows 10 versions that causes windows to become transparent. I'm running 1909 right now and can't reproduce it.

Is there any reason why you haven't updated to the latest version of Windows 10?

**Comment by RatError** [comment]
I put off for later...

**Comment by erickutcher** [comment]
I don't blame you. I've had to do the same. The second it requires a reboot to finish an update, the system fails to start. I end up having to do a reformat just to get it going again.

**Comment by RatError** [comment]
I updated when 1909 came out, everything went wrong, network drives fell off, there were problems with the video. Well managed to roll back.
Therefore, I realized - only a clean installation .
I put it off for later...
