### ISSUE TITLE
sample links which aren't properly parsed

### ISSUE THREAD

**Issue by FredThompsonII** [erickutcher/httpdownloader#127]
https://www.videohelp.com/download/Video%20Container%20Changer%20v1.3.zip - HTML page is returned, not parsed to the target file

https://bintray.com/justdan96/tsMuxer/download_file?file_path=mac-nightly-2020-03-25--01-12-53.zip - file is retrieved but name isn't proper

--

I love this downloader!!!

**Comment by erickutcher** [comment]
The first link you'll want to click on because it redirects you to a page that contains the actual download link. It'll look like this: https://www.videohelp.com/download/Video%20Container%20Changer%20v1.3.zip?r=pfrDXdrSdH

The second link is a bug. It's grabbing the filename from the redirection URL. It'll be fixed in the next release. I've changed a lot of things in the next release so your settings and history files won't work in it. It's a necessary evil to implement what I've written about here: https://github.com/erickutcher/httpdownloader/issues/59

**Comment by Zero3K** [comment]
What about importing the settings and history from the old version to the new one?

**Comment by erickutcher** [comment]
> 
> 
> What about importing the settings and history from the old version to the new one?

There's a lot of changes planned for the next release and having it read the old settings and history would just bloat the program. It's a trade off for using binary files to store the history and settings. It's fast, but inconvenient to update. I'm hoping I won't need to change any of their formats in the future.

**Comment by ncaos** [comment]
It fails to properly save the filename of downloads which include the character "]". It either cuts off everything from that point, or doesn't begin a download at all.

**Comment by erickutcher** [comment]
> 
> 
> It fails to properly save the filename of downloads which include the character "]". It either cuts off everything from that point, or doesn't begin a download at all.

Yep, that's fixed in the latest version.
