### ISSUE TITLE
Download Skipped

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#130]
Sometimes when I right-click on an image and execute 'Save image as...' command the download is skipped, screen:

![HTTP Downloader 1 0 3 1 - 2020-04-04 - skipped - 005](https://user-images.githubusercontent.com/9025757/78424522-e77a6c80-7676-11ea-91c9-4d116988f0c0.png)

When I right-click on the download and execute 'Start' command, the download completes normally, screen:

![HTTP Downloader 1 0 3 1 - 2020-04-04 - skipped - 006](https://user-images.githubusercontent.com/9025757/78424565-30322580-7677-11ea-856f-f6989b83a0cc.png)

I do not know why sometimes the downloads get skipped, this usually happens with images only.

**Example:**

1. Open this [page](http://www.guyswithtowels.com/aboutme.html);
2. Right-click on the image;
3. Execute 'Save image as...' command;
4. The download is skipped;

I do not know whether this can be reproduced.

**Comment by erickutcher** [comment]
If URLs are added remotely (from the extensions) then it gets skipped if it already exists on disk or is over 4GB in size. The reason I did this is because if you're adding URLs from the extensions on a different computer and don't have access to the computer with HTTP Downloader on it, then HTTP Downloader won't stall with a prompt asking to rename, override, or skip the download.

You can change this behavior in the Advanced Options. By default, HTTP Downloader is set to prompt if a download already exists, has been modified, or is greater than 4GB. Having an existing file be renamed would probably be the most appropriate setting.

The setting would be "When a file already exists:  Rename File"

**Comment by erickutcher** [comment]
I'm going to add an option to the extensions that'll allow you to disable it from skipping.

**Comment by smaragdus** [comment]
I have a suspicion that such skipped downloads might be related to my system- when for some reason desktop (my default download location) does not auto-refresh when a download is completed it seems that the next download sometimes gets skipped (usually an image file, although this image file has not been downloaded previously and does not appear on desktop).

**Comment by smaragdus** [comment]
Off-topic- I found a handy extension- **Image-Toolbar** ([Website](https://ht0.de/image-toolbar.html), [Chrome Web Store](https://chrome.google.com/webstore/detail/image-toolbar/cpgaepnhfockgofcejphihfafgmenofb)) for handling images on web pages. The extension is well-documented and very customizable.

**Comment by erickutcher** [comment]
There's a new setting in the extensions called "Override HTTP Downloader prompts" that'll default to whatever the program does when it come across a file that already exists or is too large.
