### ISSUE TITLE
Redirecting Downloads

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#131]
I keep a list of download links which get regular updates so when updates are available I do not visit web pages but drag&drop download links from text files onto URL drop window. But sometimes these download links change and redirect, examples:

- this [link](http://www.tomabo.net/downloads/mp4-downloader-pro-3-setup.exe) redirects to this [one](http://www.mp4apps.com/downloads/mp4-downloader-pro-3-setup.exe)
- this [link](http://www.tomabo.net/downloads/mp4-downloader-pro-3-setup.zip) redirects to this [one](http://www.mp4apps.com/downloads/mp4-downloader-pro-3-setup.zip)

When I use Free Download Manager such redirecting links are automatically updated in the download list while HTTP Downloader keeps the original links in the download list. I wonder- what about an option for such redirecting links to be automatically updated in HTTP Downloader download list?

**Comment by erickutcher** [comment]
Those links above don't redirect for me.

If the URL redirects because of a Location header value, then it should follow it properly, but the original URL that's displayed in the list won't be updated to reflect that. I have it preserve the original URL.

I can maybe make an advanced option that updates it.

**Comment by erickutcher** [comment]
I've added "Update redirected URL(s) in download list" to the Advanced options. It's disabled by default.

**Comment by smaragdus** [comment]
@erickutcher 

> Those links above don't redirect for me.

I have just checked the links and you are right- these links no longer redirect. I noticed the redirection on 2020-03-31 and if I had reported this earlier you would be able to see that these links really redirected.

> I've added "Update redirected URL(s) in download list" to the Advanced options. It's disabled by default.

This is nice, thank you! I come upon such redirecting links quire rarely and the usual redirection I have noticed is from `http` to `https`.

**Comment by erickutcher** [comment]
I've released a beta version here: https://github.com/erickutcher/httpdownloader/issues/59#issuecomment-613799125

It's a stable release as far as I can tell, but I'm going to keep the program a beta for a while. I think once I figure out how I'm going to save multi-host/mirrored downloads in the download history file, I'll implement it and upload a non-beta release. That way I can later release a version with that tree list view control and not have to update the download history file's format because of it. I'm trying to make it the least inconvenient for everyone, but these bigger features necessitate some change.

Let me know if there's any problems with the beta.

**Comment by erickutcher** [comment]
New version is up. All settings and history files will be reset since they use a new format.
