### ISSUE TITLE
Locale support

### ISSUE THREAD

**Issue by c-sanchez** [erickutcher/httpdownloader#16]
Can be nice view HTTP Downloader in other languagues in addition to english.
maybe something as "lang.ini" along with HTTP_Downloader.exe to translate the program if someone want. and/or including the translation(s) file(s) in the repository to translators :P

**Comment by erickutcher** [comment]
I've given this some thought in the past and ended up coalescing all of the translatable text into one source file. A .ini file would be the best approach when implementing it. I will consider it for a future release.

Here's all of the necessary strings in the program: https://github.com/erickutcher/httpdownloader/blob/master/HTTP_Downloader/string_tables.cpp

**Comment by erickutcher** [comment]
I will keep a reference to this and try to figure out how to implement language support. That might take a while though. I appreciate the time you took to translate it.

**Comment by erickutcher** [comment]
I've attached some files to help in creating a compatible locale file. The first is string_list.txt which contains all of the strings that are currently in the program. You'll want to go through it and translate them into your language. Make sure to keep the strings in the same order and not remove any duplicate values. Also make sure that when you save the file that it's saved in UTF-8 without the byte order mark (BOM). If you're familiar with Notepad++, then you can go into its Encoding menu and select "Encode in UTF-8" or "Convert to UTF-8".

The next file contains a program (and it's source code if you're interested) that'll convert the string_list.txt file into a locale file. It'll name the output file based on your system's current language. If it can't find a locale name, it'll default to "default". Just place the string_list.txt file in the same folder (Release) as locale_generator.exe and run the program. It's a simple command-line program that'll finish in half a second, but after it's done there will be a locale file saved to the same folder.

If you're not able to get the program working, you can just send me a copy of the translated string_list.txt file. I'll generate the locale file from it.

The locale file itself is just all of those strings with the carriage return and newline character pairs replaced with null, and all of the escaped string characters replaced with their binary equivalent.

[string_list.txt](https://github.com/erickutcher/httpdownloader/files/2498738/string_list.txt)
[locale_generator.zip](https://github.com/erickutcher/httpdownloader/files/2498739/locale_generator.zip)

**Comment by c-sanchez** [comment]
Hi @erickutcher, I apologize for the delay.
Here the Spanish locale file, I think maybe I will need improve this a bit later, but well.
haha btw, the locale generator have an small issue with Windows XP too.
**GetUserDefaultLocaleName** in **KERNEL32.dll**
[string_list.txt](https://github.com/erickutcher/httpdownloader/files/2508468/string_list.txt)

**Comment by erickutcher** [comment]
Excellent. Thanks for letting me know about that function too. It's sometimes difficult to know which functions work on older systems since Microsoft keeps changing their MSDN site.

That function is suppose to return the user's language code. Something like en-US, es-ES, de-DE, etc.

I added it to HTTP Downloader so that it could read in a language file of the same name. Since there's no equivalent function in Windows XP it won't be able to load it. That's not a problem though. If it fails to get a name or the function doesn't exist, then it'll try loading a file named "default" instead.

I'll make note of all of this and what to do when I release the next version of the program.

**Comment by c-sanchez** [comment]
Well I remember [SwiftSearch](https://sourceforge.net/projects/swiftsearch/) wich have an option to check the system locale code, and this is working with XP without any problem.
Maybe you can check SwiftSearch and find how does that :P

**Comment by erickutcher** [comment]
It's reading the values from the registry. Seems like a hack approach. There's a proper way it, but it would require some COM code. I'll look into it. It's really not critical what the file is named. I just did it this way for consistency.

**Comment by erickutcher** [comment]
I didn't include any locale files with the released, but they can be downloaded here: https://github.com/erickutcher/httpdownloader/tree/master/HTTP_Downloader/locale

Since you're on Windows XP, you'll need to rename the Spanish locale "es-ES" to "default". I opted not to add the COM code to detect the language on older systems because it's not all that important what the file is named. And setting the program up to read the locale file is a one time thing. So it shouldn't be too much of an inconvenience.

Anyway, to get the program to read the locale file, you'll want to create a folder called "locale" in the same folder as HTTP Downloader. Then just copy the locale file to that folder. Again, you'll also want to rename the locale file as "default".

**Comment by smaragdus** [comment]
@erickutcher 

What about packing the language files into an archive ('Languages.zip') and publishing it with new releases?

**Comment by erickutcher** [comment]
I suppose I can do that. I always trash extra languages when I install things because they take up unnecessary space.
