### ISSUE TITLE
It download html file, instead original exe file

### ISSUE THREAD

**Issue by shahwaliullah** [erickutcher/httpdownloader#170]
Please check:
https://www.videohelp.com/software/ShanaEncoder
https://www.videohelp.com/download/ShanaEncoder5.2.1.5.exe

Some others download managers download original file: ShanaEncoder5.2.1.5.exe
But HTTP Downloader download html file

![HTTP Download Error](https://user-images.githubusercontent.com/22966082/122123719-c222ea00-ce47-11eb-88ac-046d836e174c.PNG)

![IDM](https://user-images.githubusercontent.com/22966082/122123908-06ae8580-ce48-11eb-9b9b-266f9aa54a41.PNG)

**Comment by smaragdus** [comment]
@shahwaliullah 

I downloaded this file successfully, screen:

![HTTP Downloader 1 0 4 3 - 2021-06-16 - 002](https://user-images.githubusercontent.com/9025757/122140181-46c73580-ce53-11eb-8574-451351526284.png)

I am using [HTTP Downloader](https://erickutcher.github.io/#HTTP_Downloader) [version](https://github.com/erickutcher/httpdownloader/releases) [1.0.4.3](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.4.3).

**Comment by shahwaliullah** [comment]
I am also using version 1.0.4.3, 32bit in Windows 7 32 bit.

Still getting html file.

![HTTP Downloader](https://user-images.githubusercontent.com/22966082/122196610-d0f1b700-ceb0-11eb-816f-94cb4069f80c.PNG)

**Comment by erickutcher** [comment]
The site requires the Referer header to download the file.

When you add the link to the Add URL(s) window, click on the "Advanced options" checkbox. Click on the "Headers" tab and paste the following into the headers textbox: `Referer: https://www.videohelp.com/software/ShanaEncoder`

That should solve it.

If you use any of the browser extensions to download the link, then it'll automatically supply the Referer header. It's sometimes the case that manually adding links will fail. Normally it's because some header value is missing.

**Comment by shahwaliullah** [comment]
Thank you very much, Issue resolved by Referer.
