### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#19]
You may consider adding a change log (perhaps just a text file) which shows version history- it would make it easier to check what has changed in the new releases. Such text file might also be used for 'Update Check' if such feature is implemented in the future.

**Comment by erickutcher** [comment]
I've made an update checker in a couple other programs. It's something to consider for the future.

**Comment by c-sanchez** [comment]
Maybe something as 'changelog.txt' in the repository and/or putting the changes in the releases page instead of just 'Win32 executable' can be nice too
The changes are showed with the commit, like
https://github.com/erickutcher/httpdownloader/commit/fffc02abe2f2b1950a46a6438d527a2f88a12ced
but that is not very nice heh :P

**Comment by smaragdus** [comment]
For me a text file in the repository would be just enough- I suppose that update history in [releases](https://github.com/erickutcher/httpdownloader/releases) page is not worth the effort.

**Comment by erickutcher** [comment]
Changelog can be found here: https://github.com/erickutcher/httpdownloader/blob/master/HTTP_Downloader/changelog.txt

**Comment by smaragdus** [comment]
Thank you for the [change log](https://github.com/erickutcher/httpdownloader/blob/master/HTTP_Downloader/changelog.txt), now I can easily find what is new in the new releases.
