### ISSUE TITLE
"RUN" problems

### ISSUE THREAD

**Issue by sick13** [erickutcher/httpdownloader#22]
Adding Http Downloader's path to windows environment and running it thru "RUN" wont read the settings from the folder and creates new one in app data,for portability (i added a blank file named "portable") on the other hand clicking on the icon twice from the folder reads the settings correctly.

**Comment by smaragdus** [comment]
@sick13 

Have you tried `HTTP_Downloader.exe -p` parameter?

**Comment by erickutcher** [comment]
I've never messed with the environment variables like that, but as smaragdus said, the -p switch should work. I'll look more into this.

**Comment by sick13** [comment]
Yeap the "-p" parameter works,but if it;s not a big deal please do look into why id does not preserv setting when launched like i described

**Comment by erickutcher** [comment]
I fixed it just now. The program was using GetCurrentDirectory to determine where it was running from, but whatever executes the PATH variable has a different working directory and so that function wasn't pointing to the right place. I changed it to GetModuleFileName and now it works.

I'll release a new version some time this week to address this and some other things.

**Comment by sick13** [comment]
Great, thx for that!, btw maybe you could implement a sound notification when a download completes? would be nice but not a priority, anyway thx again for the fix,keep up the good work

**Comment by erickutcher** [comment]
I added "Play sound when all downloads finish" to the General options. When it's enabled you can select a .WAV file to play. It'll play the file when there's no more active connections and queued downloads to process.

**Comment by erickutcher** [comment]
New version is up.
