### ISSUE TITLE
Suggest providing input boxes for user agent and referer

### ISSUE THREAD

**Issue by StrollStars** [erickutcher/httpdownloader#247]
Although I can manually fill in the user agent and referer in the headers, doing so can easily lead to download failures. I hope to provide input boxes to directly enter the content.

**Comment by erickutcher** [comment]
The browser extensions can automatically fill out that information for you.

I know that a lot of sites require the user agent and referer to initiate a download, but sometimes they want other header values and it would be impossible to cater to them all. That's why I have a generic header input box.

**Comment by StrollStars** [comment]
@erickutcher However, I have a bit of an issue here. Whether it's by clicking the download button or using the right-click menu for download, the following prompt always appears:
![image](https://github.com/erickutcher/httpdownloader/assets/10942225/04f5753f-80af-431f-a8dc-82cc9cbf1730)

**Comment by erickutcher** [comment]
That message usually comes up if the Server isn't enabled in the program's Options. Open HTTP Downloader and then go into the Options window. Find the Server section on the left and then put a check in "Enable server". The default server address and port should be the same as what's set in the extensions, but if not, you'll want them to match.

**Comment by StrollStars** [comment]
@erickutcher Thank you very much, you've resolved my issue.
