### ISSUE TITLE
About drop window and toolbar

### ISSUE THREAD

**Issue by StrollStars** [erickutcher/httpdownloader#249]
1. There are multiple ways to add downloads, so the method of adding downloads by double-clicking the drop window is not used frequently. Can the double-click action be changed to open the download list?
2. Can the toolbar buttons be customized? The optional content includes menu items.

**Comment by erickutcher** [comment]
It would probably be easier to use the system tray icon to show/hide the download list. The drop window does have a context menu item to open the download list if you right click on it.

You can change the toolbar icons appearance by downloading this file and saving it into the same folder as the program: https://github.com/erickutcher/httpdownloader/raw/master/HTTP_Downloader/toolbar.bmp

Each icon is 24x24 pixels and the bright pink color is used for transparency. As far as context menu icons go, I'm probably not going to make any for them.

**Comment by StrollStars** [comment]
@erickutcher Both of them involve user habits. The drop window operation is more convenient because there are a few icons in the system tray. As for the second, I want to add an exit button to the toolbar, not to chang the button icon.

**Comment by erickutcher** [comment]
It is possible to drag a program that's in the system tray's hidden section out of it so that it can always be displayed in the row of icons. At least that's how it works on Windows 10. I think you're using Windows 7? Somewhere in the tray's settings is a way to have a program permanently display in the tray rather than hide it.

As far as the toolbar goes, I want to avoid adding an exit button because it would be redundant. The main window's close button would serve the same purpose.

**Comment by StrollStars** [comment]
@erickutcher Thank you for your reply. Let's keep this issue as it is for now because everyone has different operating habits. I am using Windows 7 and am accustomed to closing programs to the system tray. I'll change my habits a bit.
Another issue with the Site Manager, please fix it if possible.
