### ISSUE TITLE
[Feature Request] Metalink support?

### ISSUE THREAD

**Issue by maliayas** [erickutcher/httpdownloader#269]
Supporting Metalink would be a nice addition. Thanks in advance.

**Comment by maliayas** [comment]
Thanks for the reply. Actually I was considering drag&dropping the Metalink file rather than browser intercepting.

The case Metalink currently is superior to your syntax is the abilty to define custom subfolder for the file destination, such as: `<file name="lorem/ipsum.zip">`. This syntax allows to both define a custom name and also create subdirs.

In my tests, your syntax (`[custom neme here]`) is not designed for the subdirectory case yet. Maybe implementing only that rather than introducing a full xml parser to this "tiny" and powerful application is a better idea. What do you think?

**Comment by erickutcher** [comment]
I could add a new command-line parameter (_--create-output-directory_) for the Add URL(s) window that'll recreate the directory structure. Right now the _--output-directory_ switch just checks to make sure that the download directory exists.

```
[ipsum.zip]{
https://www.example.com/test.zip
https://www.example.org/test.zip
}
--create-output-directory C:\Downloads\lorem
```
So in this example the _--create-output-directory_ switch would create that directory structure if it doesn't exist and download the file to it.

I'll see what I can do with this. It might take a while since I have other projects I'm working on.

**Comment by maliayas** [comment]
Oh, somehow I missed the `--output-directory` parameter. I'll use it.

Regarding the design, instead of introducing a `--create-output-directory`, maybe `--output-directory` just should create the directory? I think that's more intuitive.

> It might take a while

Sure! Thanks for taking a look into it.

**Comment by erickutcher** [comment]
I suppose I should just have _--output-directory_ do it. Anyway, I have it implemented and I'll upload a new version this weekend.

**Comment by maliayas** [comment]
Thanks very much.

**Comment by erickutcher** [comment]
A new version is up.

It's set to use _--output-directory_ to create the folder structure.

```
[ipsum.zip]{
https://www.example.com/test.zip
https://www.example.org/test.zip
}
--output-directory C:\Downloads\lorem
```

**Comment by maliayas** [comment]
Thanks very much! Problem solved. You can close the issue as you wish.
