### ISSUE TITLE
Which one should I choose?

### ISSUE THREAD

**Issue by Dhyfer1** [erickutcher/httpdownloader#283]
Hi @erickutcher 

I am going to use httpdownloader for the first time, but in the latest release 1.0.5.8 I find 3 different files and I don't know which one to choose. So what is the difference between HTTP_Downloader, HTTP_Downloader_DM and HTTP_Downloader_LS?

Thank you in advance

**Comment by erickutcher** [comment]
HTTP_Downloader is the standard version that I have listed here: https://erickutcher.github.io/#HTTP_Downloader
I'd recommend using that.

HTTP_Downloader_DM is the dark mode version that has a darker colored theme. I don't post it on my main site because it uses unsupported Windows APIs. It should still work fine though.

HTTP_Downloader_LS is for debugging. The LS stands for "logging support" and most people would not need to use it.

**Comment by Dhyfer1** [comment]
Okay, I will always choose the standard version, thank you very much for the clarification

**Comment by Dhyfer1** [comment]
Okay, I will always choose the standard version, thank you very much for the clarification

**Comment by Dhyfer1** [comment]
@erickutcher By the way, I forgot to ask a couple of questions:

1. I see that httpdownloader is a portable app. Can you make an installer later?
2. How do I configure httpdownloader and its extension before using it for the first time?

Thanks in advance.

**Comment by erickutcher** [comment]
There's no real point for an installer since you can just delete the folder that has the program in it. If it's not run in portable mode, then the only additional folder that would need to be deleted is the `C:\Users\[user]\AppData\Local\HTTP Downloader` folder. Nothing gets written to the Windows registry either so you don't have to worry about cleaning that up.

There's a simple web server built into HTTP Downloader that allows the browser extensions to pass it the information it needs to download a URL. You'll have to enable the web server before the extensions can work. To do that go into the Options and select Server from the list on the left. In the Server options put a check in "Enable server" and then click the Apply button. There shouldn't be anything else that needs to be set unless you want to tweak the server settings.

The Firefox and Microsoft Edge extensions are in their respective add-on stores. There's a direct link to them here: https://erickutcher.github.io/#HTTP_Downloader
The Chrome extension has to be side loaded and developer mode has to be enabled for that. I wouldn't bother with it to be honest. Chrome is terrible.

**Comment by Dhyfer1** [comment]
Gotcha 🫡 Well you are right to create HTTP downloader as a portable app, I always use installers for all my programs, I rarely use a portable program, because I feel that installed programs have better performance than a portable app. Anyway, I like httpdownloader, I used IDM before and my trial has already expired, so I started looking for alternatives and I found your app, so far I have had no problems downloading files, and I'm still learning how to use some of its features.

**Comment by Dhyfer1** [comment]
Gotcha 🫡 Well you are right to create HTTP downloader as a portable app, I always use installers for all my programs, I rarely use a portable program, because I feel that installed programs have better performance than a portable app. Anyway, I like httpdownloader, I used IDM before and my trial has already expired, so I started looking for alternatives and I found your app, so far I have had no problems downloading files, and I'm still learning how to use some of its features.
