### ISSUE TITLE
Portable Mode

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#3]
Currently (as of version [1.0.0.6](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.0.6)) [HTTP Downloader](https://github.com/erickutcher/httpdownloader) saves history (**download_history**) and configuration (**http_downloader_settings**) files in AppData:

`C:\Users\User\AppData\Local\HTTP Downloader`

I would appreciate if there is an option to save history and settings files in program folder which will make **HTTP Downloader** truly portable.

Portable mode may be implemented in different ways, for example:

- **command-line argument**- if the program is started with a special parameter, for example `HTTP_Downloader.exe -portable`, history and settings are saved in program folder;
- **portable flag** - an empty file (for example **Portable**) in program folder triggers portable mode, on program start **HTTP Downloader** checks program folder for Portable flag and if it is present settings and history are saved in program folder;
- **special sub-folder** - a special sub-folder (for example **Data**) triggers portable mode, on program start **HTTP Downloader** checks program folder for this special sub-folder and if it is present settings and history are saved in program folder (perhaps in this special **Data** sub-folder);
- **check-box** - a check-box in options (**Save Data in Program Folder** or just **Portable Mode**) enables portable mode- history and settings saved in program folder.

Any of these options would be fine for me, I just need to be able to save all program data in program folder which will make **HTTP Downloader** really portable.

**Comment by erickutcher** [comment]
There actually is a portable mode. I just never got around to documenting it.

Create a shortcut to the program in the same directory. Right click on the shortcut and select Properties. In the Target textbox add a " -p" at the end of the path (excluding the quotes). Click OK when you're done. Then just run the run the shortcut whenever you want it to be portable.

**Comment by smaragdus** [comment]
@erickutcher 

Thank you for the response and for the tip. The command-line argument you mentioned (`HTTP_Downloader.exe -p`) works as expected so **HTTP Downloader** really supports portable mode. 

Enabling portable mode is easier if the program is used on a single machine only (create a shortcut and edit it) but if the user intends to use it from external drives on different machines running the program in portable mode is not that handy. You may consider adding an extra option- 'Portable' flag in program folder (next to the executable) enabling portable mode. The advantage is that once the user creates this 'Portable' flag the program will work in portable mode from any location on any machine without the need to start it with a special parameter.

Since portable mode is actually supported in the current version of **HTTP Downloader** you may close the issue. I am not closing it myself just in case you choose to add an extra option for triggering portable mode in the future.

Regards

**Comment by erickutcher** [comment]
Another solution is to create a batch file in the same directory as the program with the following line: START "" %~dp0HTTP_Downloader.exe -p

The %~dp0 will expand to the current directory of the batch file and basically gets around hard coded paths.

Only problem with that solution is it causes a command line window to open briefly before running the program.

---

I ended up coding a test for a "portable" file in the same directory as the program. If it finds it, it'll run in portable mode.

That solution will be available in the next version.

**Comment by smaragdus** [comment]
@erickutcher 

> Another solution is to create a batch file in the same directory as the program with the following line: START "" %~dp0HTTP_Downloader.exe -p
> 
> The %~dp0 will expand to the current directory of the batch file and basically gets around hard coded paths.

Thanks for the tip about the batch file, I will keep it.

> I ended up coding a test for a "portable" file in the same directory as the program. If it finds it, it'll run in portable mode.

This will be very convenient, thanks!

You may include a text file in the archive explaining how to use the program in portable mode (command-line argument, batch file, portable flag).

Since **HTTP Downloader** can be used in portable mode even now I may write a short review about the program at a forum dedicated to portable freeware. I hesitate whether to wait for the next release which will make portable use even easier.

**Comment by smaragdus** [comment]
@erickutcher 

Thank you very much for the new release. I tested version [1.0.0.7](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.0.7)- `portable` flag in program folder triggers portable mode just right. For me this option makes portable mode easier, excellent work.

As I mentioned I intended to write a short review about **HTTP Downloader** and I did it, you can find it [here](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24325), I hope I didn't miss something essential. I believe that open source software should be supported in all possible ways so I wrote this short introduction hoping that more people will discover your useful program which I came across by chance.

I presumed that **HTTP Downloader** should work under _Windows XP_ and higher, is that true?

I was also uncertain about the license under which **HTTP Downloader** is released (I could not find information about it).

Many thanks for all the help and tips and for implementing my ideas.

I find **HTTP Downloader** really useful and I may share more ideas in the future.

Regards

**Comment by erickutcher** [comment]
The license is GPLv3. I have that displayed in the Help > About menu.

As far as it working on Windows XP...it's possible, but I'm not sure as I don't have a system to test it on. I have tested it in Wine on an old version of OSX and it works reasonably well except for splitting a download into parts.

Although I aim to get my programs working on older systems, at a bare minimum, they should work on Windows Vista and newer.

I appreciate the write up. There's been a few people who have posted some of my other programs on that forum. Guess I'm doing something right.

**Comment by smaragdus** [comment]
@erickutcher 

**license**
I was in a hurry to write my review and keep my promise (taking screen-shots, uploading them, checking links, etc) so somehow I missed that the license was shown in 'About' menu (no matter that I took screen-shot of it)- I was searching license information on [HTTP Downloader](https://github.com/erickutcher/httpdownloader)) page.

**supported OS**
I have an old machine with Windows XP, I may test HTTP Downloader under Windwos XP in the future. I suppose that some users from [The Portable Freeware](https://www.portablefreeware.com/) may test it and confirm or refute whether HTTP Downloader works under Windows XP or not.

**review**
I submitted the missing or insufficient information about license and supported OS ([my new post](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24325&p=91731#p91731)).

**future**
I am not a programmer but I appreciate well-written software. Usually I need a single look at a program to conclude for me whether it is worth testing or not. What matters for me is programming language (I prefer C++ and languages from the Pascal family, I do not mind scripting languages like AutoIt and AutoHotkey, I avoid C# and absolutely abhor JavaScript+Electron), size, resource usage, features and GUI. I liked HTTP Downloader from my very first test and that was why I wanted to share my discovery. I doubt that HTTP Downloader will become extremely popular as modern day users do not use such "sophisticated" tools. I have not tested and used your other tools yet but I may have a look at them in the future- this is not a compliment but quality of programming cannot be hidden. I may share with you some more ideas about the future development of HTTP Downloader, if you don't like them there is no problem to discard them.

Regards

**Comment by smaragdus** [comment]
A user informed me that HTTP Downloader did not work under WIndows XP.

**Comment by erickutcher** [comment]
I figured as much. I've been implementing a lot of the recent suggestions you've had and some of them will limit the program to Vista and above.

I should have a new release within a week.

**Comment by smaragdus** [comment]
This is off-topic, I am posting it here because I don't want to open a new issue.
I came upon a website which **HTTP Downloader** fails to download files from- [QuickImageComment](https://www.quickimagecomment.de/index.php/en/download)- the files I get are 20 KB files without extension- for example **207-version-4-32** instead of **QuickImageComment-4.32.zip** and **208-version-4-32** in stead of **QuickImageCommentX64-4.32.zip**. Other download managers also failed. **Free Download Manager** managed to get these ZIP archives but they were corrupted. I suppose that the problem is caused by [Phoca Download](https://www.phoca.cz/phocadownload). This is not of great importance- I am just curious, do you understand what exactly is causing the problem and why only browsers can get these files without corruption?

**Comment by erickutcher** [comment]
The site is requesting the file through a POST instead of a GET request. POST requests usually contain data in their payload which isn't known unless you inspect the webpage's code. Getting the right information for a POST in an external download manager is more involved than simply copying a link.

The solution would have to involve a browser extension. Since a browser already has the information it needs, it's able to handle the download properly. An extension should be able to pass it along.

HTTP Downloader only does GET requests, like most download managers, and unless the server accepts those in lieu of a POST, it'll fail. What got downloaded was probably a webpage. If you rename it and give it a .html extension, it should open in a browser.

Implementing this would be something for the future, but it's a lot of work for 0.000001% of sites.

**Comment by smaragdus** [comment]
@erickutcher 

Thanks for the detailed explanation.

> What got downloaded was probably a webpage. If you rename it and give it a .html extension, it should open in a browser.

It seems that was the case- another download manager complained that I was trying to get a webpage.

> Implementing this would be something for the future, but it's a lot of work for 0.000001% of sites.

I agree- I download lots of files and extremely rarely I come across pages where I fail to download using download managers.

Once again, thank you for your response.

**Comment by erickutcher** [comment]
I appreciate the nice write up. It's always a surprise to me that anyone is even interested in what I make.

There's one feature that I've had implemented from the beginning that I never mentioned anywhere. If you click on the status bar values or hold Ctrl and click on any column header that displays a size value (downloaded, file size, download speed) , it'll change the measurement.

By default it's set to auto adjust so that when a size, like the speed value, gets over 1024 bytes, it sets it to 1 KB. When it gets over 1024 KB, it sets it to 1 MB, etc.

The first setting is auto, the next will have it display in bytes only, then kilobytes, megabytes, and finally gigabytes.

You'll see what happens when you do it.

You can also right click on the column headers to show or hide whichever ones you want. And you can drag and drop the column headers in whatever order you want.

Anyway, thanks again.

**Comment by smaragdus** [comment]
@erickutcher 

I am using this thread as a kind of general forum.

I like HTTP Downloader very much and I put great hope in it. I am glad I discovered it, started testing it and suggested some features. I am extremely pleased with your work, indeed. Thank you very much for all the efforts you have put on the program!

Thank you for the tip about status bar. Just a clarification- "Download speed: B/s" is shown two times- first click for 'auto' and second click for 'B/s', is that right? Thanks for the tip about the columns too.

About [1.0.0.9](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.0.9) version- this is a huge release. I am still testing it downloading random files. I will post more in the appropriate threads. In short my first impressions:

- After updating from version **1.0.0.8** to **1.0.0.9** I lost all my download history;
- The Chromium extension is working perfectly;
- There is a tiny graphical glitch about download progress- I will elaborate on it below;

In version 1.0.0.9 download progress is shown in two different ways:

- Completed
- Completed - 100.0%

screen:

![http downloader 1 0 0 9 - 2018-10-27 - completed - 003](https://user-images.githubusercontent.com/9025757/47600791-602fc080-d9cf-11e8-8ef0-409ab0778c3e.png)

I downloaded random files in all possible ways- via drop box, via new download dialog, via browser context menu, via direct click on download links (with and without confirmation) so I cannot say under what circumstances appears 'Completed - 100.0%' and when just 'Completed'. I would prefer a unified status- either 'Completed - 100.0%' or just 'Completed'. Did you add these two different statuses purposely?

Have a great week-end, after so much work you deserve a good rest!

Best regards

**Comment by erickutcher** [comment]
There's five states to the status bar. The first is auto, the next four are bytes, kilobytes, megabytes, and finally gigabytes. When it's set to auto, the unit of measurement will change as the speed ramps up. Let's say it's downloading at 100 bytes/s and then increases to 1500 bytes/s. Auto will change the 1500 bytes/s into the next higher unit which is kilobytes. 1500 bytes/s divided by 1024 bytes = 1.46 kilobytes/s. The other four states won't adjust the measurement and will show you the speed only in bytes, kilobytes, etc. So the reason you see "Download speed: B/s" twice is because it's not downloading anything at the moment and the auto state is measuring it in bytes since the speed is 0.

I had to change the download history format to add support for POST data. So the history was unfortunately lost. I don't foresee having to change it in the future though.

As for the Progress state, you'll notice the rows that don't have a percentage have a file size of "?". And when these types of downloads are downloading, they'll have an ETA of infinity. If the file size can't be determined before it starts to download (like a chunked transfer), then it's impossible to determine a percentage and ETA. They also can only use 1 active connection and can't be resumed after being stopped. It's by design to help distinguish types of transfers.

I'm glad the new version is working. I'm pleased with the overhaul to the extensions. The web browsers still need better APIs for downloads, but this will do fine. c-sanchez [reports](https://github.com/erickutcher/httpdownloader/issues/15#issuecomment-433592266) that the program is working on Windows XP as well.

**Comment by erickutcher** [comment]
I do write in other languages, but utility type programs I usually write in C++.

Normally when you preallocate a file on Windows it reserves the space until you begin writing to it. Before the first byte gets written, however, Windows will overwrite the entire space with zeros as a security precaution. This is why for large files it'll take a while to start downloading. The quick file allocation bypasses the security measure (which is why it requires administrator access) and starts writing right away.

The reason Windows writes zeros to the reserved space is to prevent unintended access to anything that might have existed in that space before (like malicious software). Recovery software uses a similar technique to restore files that were deleted.

**Comment by smaragdus** [comment]
@erickutcher 

I added **HTTP Downloader** to [The Portable Freeware Database](https://www.portablefreeware.com/index.php?id=2970), the database entry is got the necessary votes and now it is public and visible. I hope that now more users would have the chance to discover it.

Thank you for the explanation about quick file allocation.

Have a nice day

**Comment by erickutcher** [comment]
Excellent. Thanks for doing all the write ups.

**Comment by smaragdus** [comment]
@erickutcher 

Thanks for the detailed explanation and for the new version.

I updated The Portable Freeware Database [entry](https://www.portablefreeware.com/?id=2970) and made an [announcement](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24325&p=91898#p91898)  at The Portable Freeware Forum about version [1.0.1.0](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.0). I referred to your post above about video downloading. I will have to do some tests and I will comment on other threads later.

**Comment by erickutcher** [comment]
I implemented a test to have it change focus and didn't really like the behavior. Especially when a lot of URLs were added. At the moment I like to keep the state of the list and let the user decide what gets selected. Stealing focus can get annoying if it happens when you're in the middle of something. I'll keep this in mind though.

**Comment by smaragdus** [comment]
HTTP Downloader was added to [MajorGeeks](https://www.majorgeeks.com/files/details/http_downloader.html), the review is very basic and it does not list all the features of the program. Nothing is mentioned about the tool bar and the URL drop window. I didn't comment there because although I have Disqus account I do not accept their changed terms of service and privacy policy. I suppose that as now HTTP Downloader is listed at MajorGeeks it will get more attention and more people will discover this excellent download manager.

**Comment by smaragdus** [comment]
**Off-topic 1**
Why some of your other projects are hosted under different GitHub profiles?

**Off-topic 2**
For downloading of images I mostly use a program called **BilderHerunterlader**:

- [Website](http://bilderherunterlader.sourceforge.net/page/?loc=bilderherunterlader&lng=en)
- [SourceForge](https://sourceforge.net/projects/bilderherunterlader/)
- [GitHub](https://github.com/BilderHerunterlader/BilderHerunterlader)
- [AlternativeTo](https://alternativeto.net/software/bilderherunterlader/)

The program is capable but it is heavy and bulky (written in Java). It can be run in portable mode, just create `data` sub-folder and `directories.properties` file in program folder with the following contents:

```
DatabasePath=data/
SettingsPath=data/
DownloadLogPath=data/
LogsPath=data/
```

and all data and settings will be saved in `data` sub-folder in program folder.

My question- would it require too much work to build something similar but simpler in C++ which just scans web-pages for image files?

**Comment by erickutcher** [comment]
I made those other GitHub profiles back when Google Code was shutting down and wanted to have separate github.io domains for them.

I personally don't download images, so writing a program that can extract them from a site is a low priority for me. I think a more versatile approach would be to create a PHP site that can parse out the images and have it return a list of URLs. Then just copy the URLs into a download manager. Parsing HTTP requests is easy, but HTML and all the junk that comes with it is difficult. That's why something like PHP, which has all the necessary functions, would make things easier.

**Comment by smaragdus** [comment]
@erickutcher 

I came upon a Chrome extension which extracts content from webpages- [Simple mass downloader](https://chrome.google.com/webstore/detail/simple-mass-downloader/abdkkegmcbiomijcbdaodaflgehfffed), screens:

**all files:**

![simple mass downloader - 2019-01-13 - 001](https://user-images.githubusercontent.com/9025757/51085306-b0513000-173f-11e9-8ba8-55eb43bca68f.png)

**images only:**

![simple mass downloader - 2019-01-13 - 002](https://user-images.githubusercontent.com/9025757/51085309-bcd58880-173f-11e9-90e0-87e6fe5926a5.png)

**Simple mass downloader** works well with **HTTP Downloader**.

I suppose that you might find this extension useful.

Happy new year and regards.

**Comment by smaragdus** [comment]
@erickutcher 

I expected the x64 version of HTTP Downloader to use more RAM than the x32 one but it turned out that they use almost the same RAM, this was a nice surprise. Are there any real advantages of using the x64 version on x64 system?

**Comment by erickutcher** [comment]
There's probably a slight speedup, but for the most part it's unnoticeable. I decided to make a 64-bit version just because. There were only a handful of simple compiler errors to correct and then it was up and running.

**Comment by smaragdus** [comment]
@erickutcher 

HTTP Downloader was finally reviewed at [Softpedia](https://www.softpedia.com/get/Internet/Download-Managers/HTTP-Downloader.shtml)- the review is favourable (program rating- 4.5/5) but it is shallow and mediocre, There is no mention of how to enable portable mode, of URL drop window, of browser integration, etc. So far HTTP Downloader has been reviewed on the following sites:

- [Softpedia](https://www.softpedia.com/get/Internet/Download-Managers/HTTP-Downloader.shtml)
- [MajorGeeks](https://www.majorgeeks.com/files/details/http_downloader.html)
- [SnapFiles](http://www.snapfiles.com/get/httpdownloader.html)
- [The Portable Freeware](https://www.portablefreeware.com/?id=2970)
- [TrishTech](https://www.trishtech.com/2019/02/http-downloader-download-manager-for-http-https-protocol/)
- [AlternativeTo](https://alternativeto.net/software/http-downloader/)

No reviewer ever bothered to enable the nice toolbar and show it to the readers.

The only thing I miss is a way to integrate HTTP Downloader to Gecko-based browser (Palemoon, SeaMonkey) who use legacy XPI extensions. Have you ever tried [FlashGot](https://flashgot.net/)?

![FlashGot 1 5 6 13 - 2019-04-17 - 001](https://user-images.githubusercontent.com/9025757/56316533-2a3fed80-6163-11e9-9a6e-0d5991c50206.png)

![FlashGot 1 5 6 13 - 2019-04-17 - 002](https://user-images.githubusercontent.com/9025757/56316717-b3572480-6163-11e9-8013-515ca4d36c02.png)

I would appreciate even indirect browser integration via FlashGot, a way to pass the download from FlashGot to HTTP Downloader. Do you think this would be possible? By the way FlashGot can also detect video downloads.

**Comment by erickutcher** [comment]
Try this:
`[--url-list UFILE] [--cookie-string COOKIE] [--header-field Referer:REFERER]  [--header-field User-Agent:UA] [--post-data POST] [--output-directory FOLDER]`

That's all that I could get working reliably. The --output-directory switch is not working in HTTP Downloader right now. I'll fix that in the next release.

**Comment by smaragdus** [comment]
@erickutcher 

Thank you for the tip, it really works:

Passing a download from an old version of Firefox via FlashGot to HTTP Downloader:

![FlashGot 1 5 6 13 - 2019-04-19 - 001](https://user-images.githubusercontent.com/9025757/56406104-72046900-6278-11e9-854b-7667b40d16b2.png)

HTTP Downloader getting the download link:

![FlashGot 1 5 6 13 - 2019-04-19 - 003](https://user-images.githubusercontent.com/9025757/56406128-88122980-6278-11e9-8dae-1d3868d6c1c7.png)

It might not be the most elegant way but it works.

> I forgot to mention. You'll want to set **Allow only one instance of the program to run** in the Advanced options. Otherwise, you might end up spawning a ton of programs.

In fact I once opened that issue (#5) and I switched to it since it was implemented (version [1.0.0.8](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.8)), I don't know whether it is on or off by default, I suppose it should be on.

Many thanks for giving me a working placeholder for FlashGot!

Off-topic, I miss the good old days when Firefox was powerful and customizable, for me the new Quantum Firefox (since version 57) is an epic failure.

**Comment by smaragdus** [comment]
HTTP Downloader was reviewed at [gHacks](https://www.ghacks.net/2019/12/10/http-downloader-is-an-open-source-download-manager-for-windows/).

**Comment by erickutcher** [comment]
That's some good publicity. I'm bummed that I'm not going to get to release what I've worked on recently. There's some crash fixes I want to get out. My main system is dying. I think it's the motherboard...could be the power supply...maybe the CPU heat sink? No idea to be honest. It's just not stable. I built it 11 years ago and it's run pretty smoothly up until now. My hard drives are fine though. So none of my work is lost. I've been saving up for a new computer, but I'm only halfway there. Me being poor doesn't help much. :-/

**Comment by smaragdus** [comment]
@erickutcher 

> My main system is dying.

That is really a bad news. Computer dying or being unstable is a painful experience. Do you know someone who would be able to diagnose the problem? Do you have external drives so that you could backup all your stuff in case disaster strikes?

> I've been saving up for a new computer, but I'm only halfway there. Me being poor doesn't help much. :-/

I am really sorry about that! A person with your expertise and with your contribution to the open source community to be poor- this is not fair, this is not right. Unfortunately for the moment I cannot help much as I am unemployed right now.

For me HTTP Downloader is an amazing piece of software. I am glad that I have followed its development almost from the very beginning. I am curious- have you ever got any donations?

If you use Telegram or Tox or Jabber you can always contact me directly:

Telegram - https://t.me/smaragdus

Tox - C993DF91A00DF065186E04711316F27AFF106830EDB9765C61DC3EF6DA1D5F4F

Jabber - smaragdus@jabber.org

After all the exchanges about HTTP Downloader, after all your help I really feel you like a friend! Please feel free to contact me on any matter. 

I hope that you will be able to solve your computer problems soon!

**Comment by erickutcher** [comment]
I'll just take out the old hard drives and use them as storage drives in the system I'm on now.

I've gotten a $10 donation which I'm grateful for. It's always a surprise when I get anything, but I don't expect it.

We'll see where things go.

**Comment by smaragdus** [comment]
@erickutcher 

I have just sent you a small donation. I hope that the transfer is completed.

Best regards

**Comment by erickutcher** [comment]
I really appreciate that. It means a lot to me. Thank you very much. :-)

I'm going to try to get a copy of Visual Studio running on this current system and hopefully get it set up the way I had it on my old one. I'm running on a Windows 10 system right now and it's just so awful. I had to disable automatic updates because the second they have me reboot the system, the entire thing breaks and I have to reinstall it. And there's always something running in the background thrashing the disk. My Windows 7 system was as quiet as could be. Even XP was like that for me. The sooner I'm off this system, the better. :-P

**Comment by smaragdus** [comment]
II have used every single Windows version since Windows 95. I am on Windows 8 now. I once upgraded from 8 yo 8.1 but I had to downgrade again to 8 because for some reason one of my favourute old games did not work on WIndows 8.1- it was crashing so hard and was freezing the whole system that the only solution was reboot. With a few tweaking (via now abandoned Classic Shell) Windows 8 looks quite similar to Windows 7- I never see start screen, hot corners are disabled, etc. I will never switch to Windows 10- for me it is adware, spyware and botnet. I want to be in control of my system, not M$.

I really hope that you will be able to assemble a new machine as soon as possible.

I use HTTP Downloader daily- all my downloads go through it. It is a gem of a program. Currently it has all the features I would expect from a download manager. I don't get why people need speed limiter- I want to complete all my downloads as fast as possible.

If I were to study programming the languages I would choose to learn would be C/C++ and Delphi/Pascal. The most robust and the lightest programs I use are written in these languages. Just an example- I still have eMule which is more than 9 years old- it runs all the time and for these more than 9 years I have not experienced a single crash. Of course the programmer's skills are aslo important, it is just my observation that programming in C++ and in Delphi creates the smallest executables, perhaps programs written in assembler are even smaller but nowadays assembler is used extremely rarely. I am curious- have you ever studied Delphi/Pascal languages and if so- what do you think of these languages?

I wish you merry and happy upcoming holidays!

**Comment by erickutcher** [comment]
Download limiters have always been strange to me. Upload limiters are good if you're using torrents, but I'm with you...I want to download as fast as possible. Although, if you're downloading multiple files and you want one to finish first (maybe it's the first in a series and you want to start/run/play it right away), then I can see it's usefulness.

I haven't used Delphi or Pascal, but I can remember looking through some code that used it to get hints on things. It looks similar to Basic which is fairly easy to grasp if you have some programming knowledge. C and C++ are closely associated with assembly. I actually have some inline assembly in this program. I use it to get around certain limitation that result from not including the C++ runtime library in the code. That's one reason why the executable is as small as it is. I also use native Windows DLLs for various functions instead of statically linking them into the code. If I were to code this in a standard way, the program would probably be twice the size.

But here's something interesting. I used UPX to compress the 64 bit files. Now it's less than half the size of the normal release: [HTTP_Downloader_64_compressed.zip](https://github.com/erickutcher/httpdownloader/files/3981695/HTTP_Downloader_64_compressed.zip)

I hope you enjoy the holidays too.

**Comment by smaragdus** [comment]
@erickutcher 

About UPX compression I think I am not a great fan of it- is it true that UPX compressed executables start a tad slower or this is just a delusion of mine?

As I saw that you are using regular expressions I think you might find a tool I came upon at the end of last year useful- [RegExp Extractor](http://optinsoft.net/ree.php), screen:

![RegExp Extractor 1 13 Build 96 - 2020-02-27 - 001](https://user-images.githubusercontent.com/9025757/75397955-f2681180-5900-11ea-9f5a-d7d13853e8a6.png)

I am a novice and my knowledge of regular expressions is very basic. I needed to extract URLs from text files and this tool worked fine for me. Actually this was one of the few times I asked a developer for help.

To run the program in portable mode extract the installer (**Setup_REE.exe**) and run the executable (**ree.exe**) with the following parameter:

`ree.exe -appsettingsdir`

and all data and settings will be saved in program folder.

To extract URLs from text file I used the following parameters:

**Extract Conditions:**
`http=/https?://([a-z0-9][a-z0-9.-]+[a-z0-9])|(www\.[a-z0-9.-]+[a-z0-9])/i`

**Extract Rules:**
`http:$0$1`

The tool may be rather basic for you but for me it does the job as my regex needs are really basic.

**Comment by erickutcher** [comment]
I use an online tester to try out expressions. Believe me, I'm a novice when it comes to writing them. When it comes to parsing out URLs, I code it by hand. I make it a policy to only implement regular expressions as an end user feature rather than using them in code. They're actually pretty slow at processing strings. But that's all relative. If you had to process millions of URLs, it might take a few extra seconds. As for UPX executables, it should load in the same amount of time. There's probably a few milliseconds difference.

**Comment by wallace-tyrell** [comment]
> There actually is a portable mode. I just never got around to documenting it.
> 
> Create a shortcut to the program in the same directory. Right click on the shortcut and select Properties. In the Target textbox add a " -p" at the end of the path (excluding the quotes). Click OK when you're done. Then just run the run the shortcut whenever you want it to be portable.

Honestly this should be the standard behaviour. Doesn't make a lot of sense for the portable version to require a modification in order to be actually portable.
