### ISSUE TITLE
Please, make the options windows resizable, because...

### ISSUE THREAD

**Issue by maestropss** [erickutcher/httpdownloader#307]
Hi. Is it possible to make the options windows resizable or increase the spacing between lines? If the monitor scaling is 150%+, than most of options are impossible to read.

Thanks

![2024-09-19_223103](https://github.com/user-attachments/assets/17b55824-c0ef-4f10-b623-6a0e00b4f284)
![2024-09-19_223144](https://github.com/user-attachments/assets/c2671975-9615-4874-acd5-1f38037ab3ac)

**Comment by erickutcher** [comment]
Are you running the latest version of the program? (1.0.6.4)

It should scale correctly unless it's been overridden.

Here's what it looks like at 150% for me. Some of the text will look blurry since it's using GDI Scaling, but it won't cause things to get scrunched together.

![scaled](https://github.com/user-attachments/assets/c7058cc7-3e88-4bbe-bb2b-fb1bc10e0720)

**Comment by maestropss** [comment]
Hi. Thanks for the reply.

Yes, I use the latest version. In fact I had the scaling mess in the settings. I actually had (and have) 125% GDI, but the settings somehow showed 175% and this only affected the font size.

Now, I reset everything to 125% (150% is too much) and manually changed all the fonts' sizes to 12 from default 9 in the registry (9 is too small). This combination works almost fine. See attached pictures. I am happy now:)

Thanks for making and maintaining such a reasonably small (compared to similar ones) but effective app. Using command line aria2c+scripts is easy, but HTTPdownload+FF plugin is more comfortable for my old parents. 
Regards
![2024-09-20_142030](https://github.com/user-attachments/assets/273bbd26-f591-40e4-95a9-a2ca967efe8c)
