### ISSUE TITLE
Work with SingleFile Extension

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#31]
When **HTTP Downloader** is integrated with Chromium-based browsers via the extension it cannot download the files prepared by another extension- **SingleFile**:

- [GitHub](https://github.com/gildas-lormeau/SingleFile)
- [Chtome](https://chrome.google.com/webstore/detail/singlefile/mpiodijhokgodhhofbcjdecpffjipkle)
- [Forefox](https://addons.mozilla.org/en-US/firefox/addon/single-file/)

When **HTTP Downloader** extension is set to `Override browser's download manager` the HTML files created by **SingleFile** are not downloaded right, **HTTP Downloader** gets something like that (file without extension, 6 KB size):

`96a9297e-7bce-4a42-8d31-40241e26653d`

When I download the same file via the browser (`Override browser's download manager` is disabled) I got a file with a name like that:

`HTML NAME (2018-11-25 1_45_30 PM).html`

As a workaround I download the HTML file via the browser. Is it possible to make **HTTP Downloader** get the right file from **SingleFile**? If this is beyond the scope of **HTTP Downloader** please close this issue.

**Comment by erickutcher** [comment]
The file that it's serving doesn't point to an HTTP resource. It's a blob object that the browser can interpret, but not HTTP Downloader. SingleFile is constructing a blob object with all of the webpage's content in it and then it passes that object the the browser's download API. That API can handle (save) the blob object to the disk, but because HTTP Downloader intercept it before it can be saved, the object gets lost.

I suppose I could detect blob URLs and just ignore them. That way they get downloaded by whatever extension uses the download API. I'll look into it.

**Comment by smaragdus** [comment]
@erickutcher 

> I released a new version of the extensions so that they ignore any protocol that isn't http or https when overriding the browser's download manager.

This is just excellent. I tested the Chrome extension version 1.0.0.4 and it works as described. You may close this issue- on my end everything is fine now even when 'Override browser's download manager' option is chosen- the download link is skipped and the work is done by the browser.
