### ISSUE TITLE
Setting for Showing Download Speed in Mbps

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#315]
Please add a setting for displaying the `Download Speed` column in `Mbps`.

Maybe a `Speed Unit` drop down?

- MB/s
- Mbps

**Comment by erickutcher** [comment]
So rather than display it in bytes, kilobytes, megabytes, etc., you want it in bits, kilobits, megabits, etc.? I think that would look kind of strange to be honest. If a file on the system is 10 megabytes, then it would be 80 megabits. Since file systems using bytes, kilobytes, megabytes, etc. to represent file sizes, having it displayed with bits could be confusing.

If you hold Ctrl and click on the Download, File Size, or Download Speed columns, you can change the size unit.
