### ISSUE TITLE
Help with Total Commander integration

### ISSUE THREAD

**Issue by wincmd64** [erickutcher/httpdownloader#316]
I'm trying to add multi-line --url using TotalCmd environment %$CLIPBOARD%
**HTTP_Downloader.exe --url %$CLIPBOARD%**

Maybe you can help us, because it is not clear why the links are transmitted in one line?
Here is the thread with the discussion:
https://www.ghisler.ch/board/viewtopic.php?t=84364

**Comment by erickutcher** [comment]
I'll have to look into that. I don't know of a workaround at the moment.

**Comment by erickutcher** [comment]
What's happening is that your clipboard doesn't have the carriage return included with the newline character and HTTP Downloader doesn't modify the text to include it. Without the carriage return, it'll show up as one line in the ADD URL(s) edit box. Going off that thread, I would say that the issue starts with however Snap Links Plus is saving the text to the clipboard. If they're not including the carriage return and only using a newline, then it'll mess up.

Here's the line in their source code that they need to fix: https://github.com/cpriest/SnapLinksPlus/blob/5035cbcf515474cb0bbb063c7ced75d83bae1fd1/src/content-scripts/ActionMgr.js#L15

**Comment by wincmd64** [comment]
so the problem is in Snap Links Plus? 
need to open issue in he's git?

**Comment by erickutcher** [comment]
I'll need to look into my program a little more before I can give you a definitive answer.

**Comment by erickutcher** [comment]
I would go ahead and do a bug report for that extension. That specific line that I linked to should be changed to: `navigator.clipboard.writeText(links.join("\r\n"));`

What's happening is that the multiline edit control requires the carriage return and newline characters in order to display each line on its own separate row. The only way around that is to scan the text for missing carriage returns and do some potentially heavy processing to format it correctly. It's overkill when the simple solution here is for the extension to correct that one line.

**Comment by remi-garcia** [comment]
> The only way around that is to scan the text for missing carriage returns and do some potentially heavy processing to format it correctly. It's overkill when the simple solution here is for the extension to correct that one line.

`\n` should be enough as I believe this is the standard (except for Windows...)

**Comment by remi-garcia** [comment]
The change has been made on SLP side. It should just take a few days for the version release.

**Comment by remi-garcia** [comment]
SLP 3.1.14 is available. You can test that it solved your issue.

**Comment by wincmd64** [comment]
Fixed. Thx.
