### ISSUE TITLE
Fix columns autosize to it's content's width

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#32]
It would be great if the column autosize (double click column vertical separator) resized the column to it's content's width.

e.g. 
![screenshot](https://user-images.githubusercontent.com/17044982/48993520-213d8800-f192-11e8-8b2e-0c676595c781.png)

**Comment by erickutcher** [comment]
This might be tricky since I'm drawing the text on the listview control. Normally you would give the control the text for each column and it'll know how to resize things by measuring the text length. Since it doesn't have that information, it ends up resizing it to something really small. I'll see what I can do.

**Comment by hl2guide** [comment]
Thanks 💃

**Comment by erickutcher** [comment]
I got this working.

Double clicking the column separator will auto resize the column to fit its visible content. Holding Ctrl and double clicking the column separator will auto resize the column to fit its header.

**Comment by erickutcher** [comment]
New version is up.
