### ISSUE TITLE
Request/Question About *.XPI

### ISSUE THREAD

**Issue by sick13** [erickutcher/httpdownloader#35]
Is the Firefox extension compatible with Pale Moon web Browser? if not could we get support for it?

Relevant links for posting/informing about Pale Moon Extensions.

https://forum.palemoon.org/viewforum.php?f=46

Thx

**Comment by erickutcher** [comment]
As far as I'm aware, Pale Moon doesn't support the WebExtensions API. They continue to use the old Firefox API which I'm not familiar with. If anyone wants to take it up, then I don't mind. Personally, I like the standardization of the WebExtensions and Chrome/Chromium APIs.

**Comment by sick13** [comment]
yeah i thought so, Pale Moon does use the old Xul for extensions, thought id ask, maybe some wizard here can grant us support for Pale moon :)

**Comment by smaragdus** [comment]
XUL add-ons (until Firefox 56.0) could be extremely powerful and using Firefox I could do things unachievable with other browsers. Dumping the powerful XUL add-ons in favour of the feeble WebExtensions is one of the many reasons I would never use the Quantum monstrosity on my machine- countless options were removed, customization is non-existent, bugs are never addressed, the user is being spied on in all possible ways (including system add-ons), the resource usage is incredible. For me Firefox is a dead browser (just like Opera) but I still keep a very old version because it is heavily equipped with add-ons with which I can do virtually everything. If someone makes XUL add-on for HTTP Downloader it will work not only with Pale Moon but with SeaMonkey as well.

**Comment by sick13** [comment]
Yeap that's why i am using Pale Moon, like i said maybe there is a Wizard to grant as the support for this :)

**Comment by Zero3K** [comment]
Any news regarding this suggestion?

**Comment by erickutcher** [comment]
I have no plans to do an older Firefox extension. However, you can try using HTTP Downloader with [FlashGot](https://flashgot.net/).

**Comment by Zero3K** [comment]
Maybe someone else could do make one.

**Comment by Zero3K** [comment]
Maybe someone else could make one later on.

**Comment by erickutcher** [comment]
A driver would be even more work. FlashGot works fine for now.

**Comment by Zero3K** [comment]
How does the Web Extension send the URL that was clicked on to HTTP Downloader?

**Comment by erickutcher** [comment]
It sends a POST request using XMLHttpRequest.

Here's the general format for the request: https://github.com/erickutcher/httpdownloader/blob/11c817661b4f004145a82818f61728bb520325f8/HTTP_Downloader_Chrome_Extension/download.js#L96-L105

I've changed it a bit in the latest version though, but it's fairly straightforward.

**Comment by Zero3K** [comment]
No one has tried making an addon for it as of now.
