### ISSUE TITLE
request: mirror settings

### ISSUE THREAD

**Issue by FONZACUS** [erickutcher/httpdownloader#44]
ey, id like to request adding a mirror settings feature if possible. currently httpdownloader is a special kind of downloader for static content. with mirror settings per download tasks i think it could become a generalized downloader.

for example, there are some sites/hosts for example that like to expire download links every so often, with mirrors we could attempt to continue before the link expired (refresh dead links in other downloaders), and hopefully still download the file intact. or as a fail safe procedure, delete off some of the unfinished chunks and restart them with the new links.

what do you guys think?

**Comment by erickutcher** [comment]
So essentially downloading a single file with multiple hosts? Like how torrents work. It's doable, but would require a large revamp of the code.

**Comment by FONZACUS** [comment]
yep, that sums it up well. with modern internet speeds i think its not that much of a huge feature, but for when our connections are buggy it might save us some time if we can pick it back up after the original link expires.

your call though, it looks like not many others are looking in to this feature request. httpdownloader is still a nice minimal app that works just fine.

**Comment by erickutcher** [comment]
I did a little experiment to see if this could work with the current program and it worked fine.

I tested it out with an Ubuntu ISO. First I started the download and set the number of parts to 2. After it finished allocating on the disk I immediately stopped it, exported the download history, and then loaded it into a simple C# program I wrote to modify the download history files. I copied the entry in the file and modified its URL to a mirror and changed the range (parts) info so that the first URL downloaded the first half of the file, and the second URL (mirror) downloaded the second half of the file. I saved the modified download history, imported it back into HTTP Downloader, and then started both downloads. They ended up completing at around 50% (but that's because I didn't modify the file size in the download history file) and an MD5 check verified that the file was downloaded without corruption.

I think it's funny that it worked without much code change.

While it would be a neat feature, there's a lot involved with automating it in the program. I'll release the C# program at a later date for anyone who wants to manually mess around with something like this. I would caution not to rely on this way of downloading. So be sure to make backups.

**Comment by erickutcher** [comment]
I've released a new version of the program. You'll also be able to use the [History Editor](https://github.com/erickutcher/httpdownloader/releases/download/HDHE_v1.0.0.1/HDHistoryEditor.zip) with this version to modify whatever you'd like.

I did allow HTTP Downloader to update URLs after they've been added. You can right click on any entry and select Update Download... to access this. If you were to find a faster mirror for the file that's being downloaded, you can replace the current URL with it. It's not multi-host downloading (you'll need to use the history editor for that), but it does open up the option to manually set a faster host.

**Comment by FONZACUS** [comment]
thanks for the feature addition. i had a go pausing a download for a day, updated the url, and the link finished intact. swapping mirrors around also worked well.
