### ISSUE TITLE
Browser Extension: Test Connection

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#46]
A "Test Connection" button in the settings area would be useful 😃

**Comment by erickutcher** [comment]
The easiest way to test this is to access the server directly from the browser. If you're using the default host and port, then you could access it with this: http://localhost:80/

If the browser shows a blank page, then the server is running. If the browser times out or is unable to connect, then it's not running.

Ideally I'd like to turn the server into a WebSocket server. This would allow real-time updates and I could actually write a browser based client instead of just the Add URL(s) window. That's something I'll consider for the future.
