### ISSUE TITLE
Add URL(s) window

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#52]
As of version [1.0.2.1](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.2.1) **Add URL(s)** window does not resize properly when switching from **Advanced** to **Simple** mode:

**simple mode:**

![HTTP Downloader 1 0 2 1 - 2019-04-19 - 001](https://user-images.githubusercontent.com/9025757/56405248-294ab100-6274-11e9-9f6b-bb4742c063f5.png)

**advanced mode:**

![HTTP Downloader 1 0 2 1 - 2019-04-19 - 002](https://user-images.githubusercontent.com/9025757/56405265-41223500-6274-11e9-8bc1-24e815f33619.png)

**back from advanced mode to simple mode:**

![HTTP Downloader 1 0 2 1 - 2019-04-19 - 003](https://user-images.githubusercontent.com/9025757/56405306-6fa01000-6274-11e9-9561-690c19f0a44e.png)

To restore the normal size of the window in **Simple** mode after switching back from **Advanced** mode to **Simple** mode one needs to restart the program. I suppose that the window should be able to shrink back to normal size automatically.

Also, when **Add URL(s)** window is **Advanced** mode the **Advanced** button should change to **Simple**:

![HTTP Downloader 1 0 2 1 - 2019-04-19 - 004](https://user-images.githubusercontent.com/9025757/56405498-2ac8a900-6275-11e9-8e08-c61d3a47f594.png)

Of course all this is not of great importance but I suppose that it would be better if **Add URL(s)** window behaviour is fixed.

**Comment by erickutcher** [comment]
I've changed it so the window will restore its size when hiding the advanced options.

I've also changed the button to a checkbox that says "Show advanced options".

**Comment by smaragdus** [comment]
@erickutcher 

Thanks. Wouldn't just **Advanced** - **Simple** be better as it is briefer?

**Comment by erickutcher** [comment]
There's a button that I would like to use, but I'd have to draw it myself and that adds too much bulk for such a simple thing. Here's an article about Progressive Disclosure Controls: https://docs.microsoft.com/en-us/windows/desktop/uxguide/ctrl-progressive-disclosure-controls

I'd want to use an up and down single chevron button.

Since none of those are available without drawing them, a checkbox works well enough. Take a look at the Character Map program window. It has an "Advanced view" checkbox that basically does what I'm doing. I'll change the checkbox to say "Advanced options". That'll be briefer.

**Comment by smaragdus** [comment]
@erickutcher 

The check box `Advanced options` is fine for me.

Switching from `Advanced options` back to `Simple options` restores the window in its original size.

I am satisfied with the fix, thank you.
