### ISSUE TITLE
Issue with the Active Parts being shown

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#83]
Program Version: 1.0.2.6 (32-bit)

When I changed the number of parts for the download to use via the Update Download context-menu item, it shows as 1/1/8 (for example). I think it should show 1/1 unless its intentional (and showing that 8 parts is the globally set option).

**Comment by erickutcher** [comment]
It's intentional, I just never documented it. The first number is the active part. The second is the limit (the value you set in Update Download), and the last one is the total number of parts that were originally set.

It's basically there to inform you that there's an active part limit being imposed.

**Comment by Zero3K** [comment]
Maybe you should document it then.
